import { useEffect, useState } from "react";
import {
  getGoldReconciliationAnalytics,
  getOperatorAnalytics,
  getProductionInsights,
  getQualityAnalytics,
  getUsers,
  getWipStatus,
} from "../services/api";

function Analytics() {
  const [wip, setWip] = useState(null);
  const [goldRecon, setGoldRecon] = useState(null);
  const [qualityStats, setQualityStats] = useState(null);
  const [insights, setInsights] = useState(null);
  const [insightsLoading, setInsightsLoading] = useState(false);
  const [operators, setOperators] = useState([]);
  const [selectedOp, setSelectedOp] = useState("");
  const [opStats, setOpStats] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    async function load() {
      try {
        setLoading(true);
        const [wipData, reconData, qualData, insightData, userData] = await Promise.all([
          getWipStatus(),
          getGoldReconciliationAnalytics(),
          getQualityAnalytics(),
          getProductionInsights(),
          getUsers(),
        ]);
        setWip(wipData.wip);
        setGoldRecon(reconData);
        setQualityStats(qualData);
        setInsights(insightData.ai_insights || null);
        setOperators(userData);
      } catch (e) {
        setError(e.message);
      } finally {
        setLoading(false);
      }
    }
    load();
  }, []);

  async function refreshInsights() {
    setInsightsLoading(true);
    try {
      const data = await getProductionInsights();
      setInsights(data.ai_insights || null);
    } catch (e) {
      setError(e.message);
    } finally {
      setInsightsLoading(false);
    }
  }

  async function loadOperatorStats() {
    if (!selectedOp) return;
    try {
      const stats = await getOperatorAnalytics(selectedOp);
      setOpStats(stats);
    } catch (e) {
      setError(e.message);
    }
  }

  if (loading) return <section className="page"><div className="state-message">Loading analytics...</div></section>;

  const stagesOrder = ["Registered", "Casting", "Filing", "Stone Setting", "Polishing", "Plating"];

  return (
    <section className="page">
      <div className="page-header">
        <p className="page-label">LIVE COMMAND CENTER</p>
        <h1>Production Analytics</h1>
        <p>Real-time WIP visibility, gold reconciliation, quality gate stats, and operator performance scores.</p>
      </div>

      {error && <div className="form-message form-error" style={{ marginTop: "16px" }}>{error}</div>}

      {/* AI-Powered Insights */}
      <div className="content-section" style={{ background: "#f0f5ff", borderColor: "#c8d9f5" }}>
        <div className="section-header">
          <div>
            <h2 style={{ color: "#1a4a8a" }}>🤖 AI Production Insights</h2>
            <p>Natural language analysis generated by Groq's reasoning model (openai/gpt-oss-120b).</p>
          </div>
          <button className="primary-button" style={{ background: "#1a4a8a" }} onClick={refreshInsights} disabled={insightsLoading}>
            {insightsLoading ? "Generating..." : "Refresh"}
          </button>
        </div>

        {insights ? (
          <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
            <div style={{ padding: "16px", background: "#fff", borderRadius: "10px", border: "1px solid #d9e5f5" }}>
              <p style={{ fontSize: "13px", fontWeight: 700, color: "#1a4a8a", marginBottom: "6px" }}>Overall Assessment</p>
              <p style={{ fontSize: "14px", color: "#3d485a", lineHeight: 1.7 }}>{insights.overall_assessment}</p>
            </div>

            {insights.bottlenecks && insights.bottlenecks.length > 0 && (
              <div style={{ padding: "16px", background: "#fff5f5", borderRadius: "10px", border: "1px solid #f0cccc" }}>
                <p style={{ fontSize: "13px", fontWeight: 700, color: "#b14343", marginBottom: "6px" }}>⚠️ Bottlenecks</p>
                <ul style={{ marginLeft: "16px", fontSize: "14px", color: "#3d485a", lineHeight: 1.7 }}>
                  {insights.bottlenecks.map((b, i) => <li key={i}>{b}</li>)}
                </ul>
              </div>
            )}

            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px" }}>
              <div style={{ padding: "16px", background: "#fff", borderRadius: "10px", border: "1px solid #d9e5f5" }}>
                <p style={{ fontSize: "13px", fontWeight: 700, color: "#1a4a8a", marginBottom: "6px" }}>Quality Insight</p>
                <p style={{ fontSize: "14px", color: "#3d485a", lineHeight: 1.6 }}>{insights.quality_insight}</p>
              </div>
              <div style={{ padding: "16px", background: "#edf7f1", borderRadius: "10px", border: "1px solid #c8e8d5" }}>
                <p style={{ fontSize: "13px", fontWeight: 700, color: "#287a50", marginBottom: "6px" }}>Recommendation</p>
                <p style={{ fontSize: "14px", color: "#3d485a", lineHeight: 1.6 }}>{insights.recommendation}</p>
              </div>
            </div>

            <div style={{ textAlign: "right" }}>
              <span className="record-count">Groq GPT-OSS-120b</span>
            </div>
          </div>
        ) : (
          <div className="state-message">Loading AI insights...</div>
        )}
      </div>

      {/* WIP Dashboard */}
      <div className="content-section">
        <div className="section-header">
          <div>
            <h2>Work-in-Progress</h2>
            <p>Pieces at each manufacturing stage right now.</p>
          </div>
        </div>

        {wip ? (
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: "16px" }}>
            {wip
              .filter((s) => stagesOrder.includes(s.stage))
              .sort((a, b) => stagesOrder.indexOf(a.stage) - stagesOrder.indexOf(b.stage))
              .map((stage) => (
                <div key={stage.stage} style={{
                  background: stage.piece_count > 0 ? "#172033" : "#f5f7fa",
                  color: stage.piece_count > 0 ? "#fff" : "#687386",
                  borderRadius: "12px",
                  padding: "20px",
                  textAlign: "center",
                }}>
                  <div style={{ fontSize: "12px", fontWeight: 700, letterSpacing: "0.5px", marginBottom: "8px", opacity: 0.7 }}>
                    {stage.stage}
                  </div>
                  <div style={{ fontSize: "32px", fontWeight: 800 }}>
                    {stage.piece_count}
                  </div>
                  <div style={{ fontSize: "13px", marginTop: "4px", opacity: 0.7 }}>
                    {stage.piece_count === 1 ? "piece" : "pieces"}
                  </div>
                </div>
              ))}
          </div>
        ) : (
          <div className="state-message">No WIP data available.</div>
        )}
      </div>

      {/* Gold Reconciliation */}
      <div className="content-section">
        <div className="section-header">
          <div>
            <h2>Gold Reconciliation</h2>
            <p>Stage-wise gold loss/gain tracking across production.</p>
          </div>
          {goldRecon && (
            <div className="record-count">
              Total Δ: {goldRecon.total_variance.toFixed(2)}g
            </div>
          )}
        </div>

        {goldRecon && goldRecon.stages.length > 0 ? (
          <div className="table-container">
            <table className="data-table">
              <thead>
                <tr>
                  <th>Stage</th>
                  <th>Pieces</th>
                  <th>Weight In (g)</th>
                  <th>Weight Out (g)</th>
                  <th>Expected (g)</th>
                  <th>Variance (g)</th>
                  <th>Avg Variance</th>
                </tr>
              </thead>
              <tbody>
                {goldRecon.stages.map((s) => (
                  <tr key={s.stage}>
                    <td><span style={{ fontWeight: 600 }}>{s.stage}</span></td>
                    <td>{s.total_pieces}</td>
                    <td>{s.total_weight_in.toFixed(2)}</td>
                    <td>{s.total_weight_out.toFixed(2)}</td>
                    <td>{s.total_expected != null ? s.total_expected.toFixed(2) : "—"}</td>
                    <td style={{ color: s.total_variance < 0 ? "#b14343" : "#287a50", fontWeight: 600 }}>
                      {s.total_variance.toFixed(2)}g
                    </td>
                    <td>{s.average_variance_per_piece.toFixed(3)}g</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="state-message">No weight data recorded yet.</div>
        )}
      </div>

      {/* Quality Stats */}
      <div className="content-section">
        <div className="section-header">
          <div>
            <h2>Quality Gate Statistics</h2>
            <p>AI inspection summary across all checkpoints.</p>
          </div>
        </div>

        {qualityStats && qualityStats.total_gates > 0 ? (
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: "16px" }}>
            <div style={{ background: "#edf7f1", borderRadius: "12px", padding: "20px", textAlign: "center" }}>
              <div style={{ fontSize: "12px", fontWeight: 700, color: "#287a50", marginBottom: "8px" }}>PASSED</div>
              <div style={{ fontSize: "32px", fontWeight: 800, color: "#287a50" }}>{qualityStats.pass_count}</div>
              <div style={{ fontSize: "13px", color: "#287a50", marginTop: "4px" }}>{(qualityStats.pass_rate * 100).toFixed(1)}%</div>
            </div>
            <div style={{ background: "#fef9ee", borderRadius: "12px", padding: "20px", textAlign: "center" }}>
              <div style={{ fontSize: "12px", fontWeight: 700, color: "#b8891d", marginBottom: "8px" }}>FLAGGED</div>
              <div style={{ fontSize: "32px", fontWeight: 800, color: "#b8891d" }}>{qualityStats.flag_count}</div>
              <div style={{ fontSize: "13px", color: "#b8891d", marginTop: "4px" }}>needs review</div>
            </div>
            <div style={{ background: "#fff5f5", borderRadius: "12px", padding: "20px", textAlign: "center" }}>
              <div style={{ fontSize: "12px", fontWeight: 700, color: "#b14343", marginBottom: "8px" }}>FAILED</div>
              <div style={{ fontSize: "32px", fontWeight: 800, color: "#b14343" }}>{qualityStats.fail_count}</div>
              <div style={{ fontSize: "13px", color: "#b14343", marginTop: "4px" }}>rejected</div>
            </div>
          </div>
        ) : (
          <div className="state-message">No quality inspections recorded yet.</div>
        )}

        {qualityStats && qualityStats.top_defects && qualityStats.top_defects.length > 0 && (
          <div style={{ marginTop: "20px" }}>
            <h3 style={{ marginBottom: "10px", fontSize: "15px", color: "#3d485a" }}>Top Defects</h3>
            <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
              {qualityStats.top_defects.map((d, i) => (
                <span key={i} className="role-badge" style={{ background: "#fff5f5", color: "#b14343" }}>
                  {d}
                </span>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Operator Scores */}
      <div className="content-section">
        <div className="section-header">
          <div>
            <h2>Operator Performance</h2>
            <p>Select an operator to view quality scores, throughput, and wastage history.</p>
          </div>
        </div>

        <div style={{ display: "flex", gap: "12px", marginBottom: "18px", alignItems: "end" }}>
          <div className="form-group" style={{ maxWidth: "300px" }}>
            <label>Operator</label>
            <select value={selectedOp} onChange={(e) => setSelectedOp(e.target.value)}>
              <option value="">Select operator</option>
              {operators.map((op) => <option key={op.id} value={op.operator_id}>{op.operator_id} — {op.name}</option>)}
            </select>
          </div>
          <button className="primary-button" onClick={loadOperatorStats} disabled={!selectedOp}>
            Load Stats
          </button>
        </div>

        {opStats && !opStats.error && (
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: "16px" }}>
            <div style={{ background: "#f5f7fa", borderRadius: "12px", padding: "20px", textAlign: "center" }}>
              <div style={{ fontSize: "12px", fontWeight: 700, color: "#687386", marginBottom: "8px" }}>PIECES WORKED</div>
              <div style={{ fontSize: "32px", fontWeight: 800, color: "#172033" }}>{opStats.total_pieces_worked}</div>
            </div>
            <div style={{ background: "#f5f7fa", borderRadius: "12px", padding: "20px", textAlign: "center" }}>
              <div style={{ fontSize: "12px", fontWeight: 700, color: "#687386", marginBottom: "8px" }}>TOTAL EVENTS</div>
              <div style={{ fontSize: "32px", fontWeight: 800, color: "#172033" }}>{opStats.total_events}</div>
            </div>
            <div style={{ background: "#f5f7fa", borderRadius: "12px", padding: "20px", textAlign: "center" }}>
              <div style={{ fontSize: "12px", fontWeight: 700, color: "#687386", marginBottom: "8px" }}>AVG WASTAGE</div>
              <div style={{ fontSize: "32px", fontWeight: 800, color: opStats.average_wastage < 0 ? "#b14343" : "#287a50" }}>
                {opStats.average_wastage.toFixed(2)}g
              </div>
            </div>
            <div style={{ background: "#f5f7fa", borderRadius: "12px", padding: "20px", textAlign: "center" }}>
              <div style={{ fontSize: "12px", fontWeight: 700, color: "#687386", marginBottom: "8px" }}>QUALITY PASS RATE</div>
              <div style={{ fontSize: "32px", fontWeight: 800, color: opStats.quality_pass_rate > 0.7 ? "#287a50" : "#b14343" }}>
                {(opStats.quality_pass_rate * 100).toFixed(0)}%
              </div>
            </div>
          </div>
        )}

        {opStats && opStats.error && <div className="state-message error-message">{opStats.error}</div>}
        {!opStats && selectedOp && <div className="state-message">Click &quot;Load Stats&quot; to view operator data.</div>}
      </div>
    </section>
  );
}

export default Analytics;
